### ISSUE TITLE
Mobile/Low End Device Friendly Page

### ISSUE THREAD

**Issue by Frozen-byte** [fankserver/website#11]
App is not starting on my **Sony Xperia ARC**(LT15i) running Android 4.0.4
Nor on my **Tokio Love Tablet**(v3.0)running Android 4.2.2
Just shows white page telling "Starting App..."

Tried with following Browsers:
- Lightning Browser version 4.2.3a
- Tablet Stock browser version 4.2.2

This issue may includes #8

**Comment by fank** [comment]
Can you please provide os version & browser type + version?

**Comment by Frozen-byte** [comment]
Edited OP with more device and software information.

In before "have you enablded JavaScript?" - Yes I am.

**Comment by bitflip2** [comment]
@Frozen-byte Do you still experience this issue?

**Comment by Frozen-byte** [comment]
Yes, the Issue is still valid on both devices.
I will try to get a Debug log when I'm back from vacation.

**Comment by bitflip2** [comment]
Great. Thanks.
Am 25.02.2016 12:53 schrieb "Frozen_byte" notifications@github.com:
