### ISSUE TITLE
Impossible to login/register on mobile devices

### ISSUE THREAD

**Issue by bitflip2** [fankserver/website#8]
It is impossible to login or register on mobile devices or devices with a small screen, because the buttons are not rendered (or rendered off-screen)

**Comment by bitflip2** [comment]
Could we raise the priority of this issue?

**Comment by fank** [comment]
@nano2K I'm unable to reproduce this issue, could you provide some information?
- Which browser are you using?
- Which OS are you using?

**Comment by bitflip2** [comment]
OS: Android 5.1.1
Browser: Chrome 48.0.2564.95

But this issue seems to be OS independent. Just resize your browser window

**Comment by bitflip2** [comment]
http://imgur.com/Ut36bGA

**Comment by fank** [comment]
Should be fixed

**Comment by bitflip2** [comment]
Confirmed, thank you
